.github/workflows/release-publish.yml
src/main.ts
src/module.playground/_module.ts

fixed playground reset
enabled cors
/kind chore
- Fixed playground not to reset 
- Enabled COR by default
- Fixed publish script version not allowing double-digit version

enable cors, fixed playground and publish script

---

src/module.playground/setup/setup.ts

/kind chore
setup generateToAddress to run at 200ms interval so that defid logs are not polluted

setup generateToAddress to run at 200ms interval

---

packages/playground-api-client/__tests__/api/stats.test.ts
packages/playground-api-client/src/api/stats.ts
packages/playground-api-client/src/index.ts
packages/playground-api-client/src/playground.api.client.ts
src/module.api/_module.ts
src/module.api/stats.controller.ts

added status controller for playground reporting for testing QOL

---

__sanity__/docker-compose.yml
packages/playground-api-client/src/playground.api.client.ts

update docker-compose.yml as playground network is not allowed in whale

---

.github/CODEOWNERS
.github/workflows/oss-governance-project-pr.yml

/kind chore
Updated CODEOWNERS to include product maintainer and jellyfish ecosystem maintainer.

updated CODEOWNERS

---

.github/workflows/defichain-dependencies.yml
package.json

improved @defichain/* update workflow

---

packages/playground-api-client/src/errors/api.error.ts

removed illegal `import { HttpStatus } from '@nestjs/common'` in packages

---

__sanity__/docker-compose.yml
__sanity__/postman_collection.json
packages/playground-api-client/__tests__/api/rpc.test.ts
packages/playground-api-client/__tests__/stub.client.ts
packages/playground-api-client/src/playground.api.client.ts
src/module.api/_core/api.version.ts
src/module.api/playground.controller.ts
src/module.api/rpc.controller.ts

/kind feature
refactor v1 to v0 to follow the current release track of 0.x.x

refactor v1 to v0 to follow the current release track of 0.x.x

---

src/main.ts

/kind feature
allow port to be override to allow flexible deployment

allow port to be override to allow flexible deployment

---

src/module.playground/_module.ts

increased default wait for DeFiD to 45s

---

src/module.playground/_module.e2e.ts
src/module.playground/_module.ts
src/module.playground/setup/setup.oracle.ts

Add oracle setup

---

src/module.playground/setup/setup.oracle.ts
src/module.playground/setup/setup.ts

/kind fix
This modifies setup to use the owner address as this has prevouts to perform "update" functionality, and bech32 keys to support signing updates to poolpairs/oracles via txn-builder
EDIT: Slight modification, see comment below
Fixes #

Use bech32 MN keys and owner address

---

.github/workflows/nestjs-dependencies.yml

Added @nestjs deps update workflow

---

.github/workflows/defichain-dependencies.yml
.github/workflows/nestjs-dependencies.yml

fixed workflow naming

---

packages/playground-api-client/__tests__/api/wallet.test.ts
packages/playground-api-client/src/api/playground.ts
packages/playground-api-client/src/api/wallet.ts
packages/playground-api-client/src/playground.api.client.ts
src/module.api/_module.ts
src/module.api/playground.controller.ts
src/module.api/wallet.controller.ts

/kind refactor
refactor `/wallet` into `wallet.controller.ts` as `/wallet/balances`.

refactor `/wallet` into `wallet.controller.ts`

---

package-lock.json
package.json
packages/playground-api-client/__tests__/api/wallet.test.ts
packages/playground-api-client/src/api/wallet.ts
src/module.api/wallet.controller.ts
src/module.playground/setup/setup.ts

/kind feature
```ts
await client.wallet.sendTokenDfiToAddress({
address: 'bcrt1qgpu5k3v66qjf8lc4p4lny0uwdxv6vf94axnjkf',
amount: '10'
})
```
Fixes #67

sendTokenDfiToAddress endpoint to allow sending of Token DFI to any address with simple API call

---

packages/playground-api-client/__tests__/api/wallet.test.ts
src/module.api/wallet.controller.ts

/kind feature
Added `"wallet/tokens/0/sendtoaddress"` for future adaption of `wallet/tokens/:id/sendtoaddress`. This new endpoint will wait for automated block confirmation for the created transaction.

added "wallet/tokens/:id/sendtoaddress"

---

.github/workflows/release-publish.yml

fixed id: version release

---

.github/workflows/ci/docker-compose.yml

update image: defi/defichain:1.7.11

---

.github/workflows/ci/docker-compose.yml

Bump `whale:0.6.0`

---

.github/workflows/ci/docker-compose.yml

bump defi/defichain:1.8.0

---

.github/workflows/ci/docker-compose.yml

fixed pathprefix routing

---

package-lock.json
package.json
src/module.playground/_module.e2e.ts
src/module.playground/_module.ts
src/module.playground/setup/setup.masternode.ts
src/module.playground/setup/setup.oracle.ts
src/module.playground/setup/setup.ts

/kind feature
- Added `MasternodeSetup`.
- Added all `GenesisKey` into Playground to access all funds.

Added `SetupMasternode` for adding of 2 MN into playground

---

src/module.playground/_module.e2e.ts
src/module.playground/_module.ts

added rescan to fix missing balance

---

packages/playground-api-client/__tests__/api/wallet.test.ts
packages/playground-api-client/src/errors/index.ts
src/module.playground/_module.e2e.ts
src/module.playground/setup/setup.dex.ts
src/module.playground/setup/setup.token.ts

added USDC to playground

---

packages/playground-api-client/src/errors/index.ts

fixed wrong import use in playground-api-client

---

.github/CODEOWNERS
.github/workflows/ci/docker-compose.yml
src/module.api/interceptors/exception.interceptor.ts

added exception logging to playground

---

src/module.playground/setup/setup.dex.ts

reversed PoolPair a/b symbol to DFI last

---

src/module.playground/_module.e2e.ts
src/module.playground/_module.ts
src/module.playground/bot/bot.ts
src/module.playground/bot/oracle.bot.e2e.ts
src/module.playground/bot/oracle.bot.ts
src/module.playground/setup/setup.oracle.ts

/kind feature
Adds `set-oracle-data` bot
Fixes #

`set-oracle-data` bot

---

src/module.api/rpc.controller.ts

/kind chore
To open up playground network for easier testing for new features.

convert whitelist to blacklist for playground RPC

---

packages/playground-api-client/__tests__/stub.service.ts
src/e2e.module.ts

Point all container to use MasterNodeRegTestContainer

---

src/module.playground/setup/setup.loan.collateral.ts

updated collateral factor to reflect the vault in pink paper

---

src/module.playground/bot/oracle.bot.ts

add oracle.bot.ts 33% drastic random price moment to allow HALTED state

---

.github/workflows/ci.yml
.github/workflows/ci/docker-compose.yml
packages/playground-api-client/__tests__/api/wallet.test.ts
src/module.playground/_module.e2e.ts
src/module.playground/_module.ts
src/module.playground/bot/oracle.bot.e2e.ts
src/module.playground/bot/oracle.bot.ts
src/module.playground/setup/setup.dex.ts
src/module.playground/setup/setup.loan.collateral.ts
src/module.playground/setup/setup.loan.scheme.ts
src/module.playground/setup/setup.loan.token.ts
src/module.playground/setup/setup.masternode.ts
src/module.playground/setup/setup.oracle.ts
src/module.playground/setup/setup.ts

/kind feature
Required for Loan Payback

updated dex setup to include Loan PoolPair

---

packages/playground-api-client/__tests__/api/wallet.test.ts
src/module.playground/_module.ts
src/module.playground/bot/oracle.bot.ts
src/module.playground/bot/vault.bot.e2e.ts
src/module.playground/bot/vault.bot.ts

add vault bot

---

src/module.playground/bot/oracle.bot.ts

fix oracle.bot.ts failing to publish due to lower than 0 price

---

.github/workflows/defichain-dependencies.yml

/kind 
fix defichain-dependencies.yml not updating all package.json

fix defichain-dependencies.yml not updating all package.json

---

.idea/dictionaries/fuxing.xml
src/module.playground/bot/oracle.bot.ts

tune oracle bot to push price update slower

---

.idea/dictionaries/fuxing.xml
src/module.playground/bot/vault.bot.e2e.ts
src/module.playground/bot/vault.bot.ts

vault.bot.ts to loan all tokens and add to DEX

---

.github/workflows/ci/docker-compose.yml

bump(docker-compose.yml): defi/defichain:2.6.0

---

.github/workflows/ci/docker-compose.yml
src/module.playground/_module.e2e.ts
src/module.playground/_module.ts
src/module.playground/setup/setup.gov.ts
src/module.playground/setup/setup.loan.collateral.ts

/kind feature
Add DUSD collateral token
Enable DFI to pay DUSD loan by manually setgov for now
Fixes #

feat(playground-mod): set payback dusd by dfi & add dusd collateral token

---

jest.config.js
src/module.playground/_module.e2e.ts
src/module.playground/bot/oracle.bot.ts
src/module.playground/setup/setup.dex.ts
src/module.playground/setup/setup.loan.collateral.ts
src/module.playground/setup/setup.oracle.ts
src/module.playground/setup/setup.token.ts

feat(module.playground): add zero liquidity pool pair
